version: '3'
services:
  production:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
  development:
    build:
      context: .
      dockerfile: Dockerfile-development
    ports:
      - "8080:80"
    volumes:
      - .:/app
